# Travis build integration.
# https://docs.travis-ci.com/

language: cpp
# Order here matters for implicit matrix generation and coverity scan.
# See travis/main.sh for details.
compiler:
  - gcc
  - clang

env:
  global:
   # COVERITY_SCAN_TOKEN
   - secure: "h7NGklk0xX2iuY5PgxijE7FFEgd95hxbhSwofs+hzYIiW6FR2kk8gSwEqRH5dYGnvazGT3a7fjxuYAr0y5BQCfV7yyQISl19rYZPJbP9bTxGxijTGlItyQqVTXCaucuXzgJbAOgC1W3ja4lYODflCyFzHhPggJLkXEAw1FF3+5M="
   - CODECOV_TOKEN=:118ede5b-753f-46e3-a5c7-3f898836b441
   - coverage=yes
   - CFLAGS="-lrt -ftest-coverage -fprofile-arcs "
   - LDFLAGS+="-lgcov "
sudo: false

# Order here matters; see compiler comment above.
os:
  - linux
#  - osx

script: ./travis/main.sh

addons:
  apt:
    packages:
    - nasm
    - naturaldocs
    - libpng-dev
    - libz-dev
    - libjpeg-dev
    - libfreetype6-dev
    - libxpm-dev
    - libx11-dev
    - libxt-dev
    - libfontconfig-dev
    - libvpx-dev
    - libtiff-dev
    - libwebp-dev
    - automake
    - autoconf
    - libtool
    - html2text
    - lcov
after_failure:
        - cat "$TRAVIS_BUILD_DIR"/builddir/meson-logs/testlog.txt
after_success: 
        # Creating report
        - cd ${TRAVIS_BUILD_DIR}
        - lcov --directory . --capture --output-file coverage.info # capture coverage info
        - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out system
        - lcov --list coverage.info #debug info
        - codecov -t 39285ee5-9536-44ee-8d9c-2f1a46e851e5
